services:
  # Postgres service
  db:
    # Image to be pulled from Docker Hub
    image: postgres
    restart: always
    # Environment variables
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: maximus

    ports:
      - 5432:5432
    # Volume to persist the data even after the container is stopped
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
    # Healthcheck command because other containers depend on this one
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']

  admin:
    image: vishalacharya221997335/mx-admin
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile.admin
    ports:
      - 80:80

  api:
    image: vishalacharya221997335/mx-api
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile.api
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - JWT_SECRET=${JWT_SECRET}
      - RAZORPAY_KEY=${RAZORPAY_KEY}
      - RAZORPAY_SECRET=${RAZORPAY_SECRET}
    restart: on-failure:10
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
