version: '3'

services:
  # Postgres service
  db:
    # Image to be pulled from Docker Hub
    image: postgres
    restart: always
    # Environment variables
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: maximus
    # Ports used, format: <host_port>:<container_port>
    ports:
      - 5432:5432
    # Volume to persist the data even after the container is stopped
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
    # Healthcheck command because other containers depend on this one
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']

  admin:
    build:
      context: ./
      dockerfile: Dockerfile.admin
    ports:
      - 80:80

  api:
    build:
      context: './'
      dockerfile: Dockerfile.api
    env_file:
      - .env
    restart: on-failure:10
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
