# FROM docker.io/node:lts-alpine

# WORKDIR /app

# COPY dist/apps/admin/browser admin

# RUN npm i -g serve

# EXPOSE 3000

# CMD [ "serve", "admin"]

FROM nginx:alpine

COPY dist/apps/admin/browser /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
