services:
  # Postgres service
  db:
    # Image to be pulled from Docker Hub
    image: postgres
    restart: always
    # Environment variables
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: maximus

    ports:
      - 5432:5432
    # Volume to persist the data even after the container is stopped
    volumes:
      - ./app-data/data/postgres:/var/lib/postgresql/data
    # Healthcheck command because other containers depend on this one
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    volumes:
      - ./app-data/redis_data:/data

  api:
    image: vishal2457/mx-api
    build:
      context: ./
      dockerfile: ./infra/Dockerfile.api
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - JWT_SECRET=${JWT_SECRET}
      - RAZORPAY_KEY=${RAZORPAY_KEY}
      - RAZORPAY_SECRET=${RAZORPAY_SECRET}
    volumes:
      - ./app-data/api/images:/app/mx-images
      - ./app-data/api/logs:/app/logs
    expose:
      - 3000
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
    depends_on:
      - db
      - redis

  nginx:
    image: vishal2457/mx-nginx
    build:
      context: ./
      dockerfile: ./infra/Dockerfile.nginx
    ports:
      - 3000:3000
      - 80:80
    depends_on:
      - api
