# FROM docker.io/node:lts-alpine

# WORKDIR /app

# COPY dist/apps/admin/browser admin

# RUN npm i -g serve

# EXPOSE 3000

# CMD [ "serve", "admin"]

FROM nginx:alpine

COPY dist/apps/admin/browser /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY /infra/nginx.conf  /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 3000


CMD ["nginx", "-g", "daemon off;"]
