FROM nginx:alpine

COPY dist/apps/admin/browser /usr/share/nginx/html/app
COPY /member-web-build/dist /usr/share/nginx/html/member-app
COPY /landing-page-build/out /usr/share/nginx/html/landing-page

RUN rm /etc/nginx/conf.d/default.conf
COPY /infra/nginx.conf  /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443
# EXPOSE 4200
# EXPOSE 4300

CMD ["nginx", "-g", "daemon off;"]
