
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3001

WORKDIR /app
# Install build tools
# RUN apk add --no-cache make gcc g++ python3

COPY dist/apps/api api

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix api i --no-audit --progress=false
EXPOSE 3001

CMD [ "node", "api" ]
