FROM nginx:alpine

COPY dist/apps/admin/browser /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY /infra/nginx.conf  /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 3000


CMD ["nginx", "-g", "daemon off;"]
