global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pg_exporter'
    static_configs:
      - targets: ['pg_exporter:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.25.64.1:3000']
