version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: mx_redis_container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
