name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'npm'
      - name: Set env variables
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "NODE_HOST=${{ secrets.NODE_HOST }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY }}" >> $GITHUB_ENV
          echo "RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET }}" >> $GITHUB_ENV
          echo "FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID }}" >> $GITHUB_ENV

      - name: install dependencies
        run: npm ci --no-audit --progress=false

      - name: Preparing production build
        run: npm run build:all

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: docker compose -f docker-compose.prod.yml --profile prod build

      - name: Push Docker image
        run: docker compose -f docker-compose.prod.yml --profile prod push

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Copy docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.NODE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: './docker-compose.prod.yml'
          target: '/root/mx'
          overwrite: true

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NODE_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /root/mx
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export DB_USERNAME=${{ secrets.DB_USERNAME}}
            export DB_PORT=${{ secrets.DB_PORT}}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD}}
            export NODE_HOST=${{ secrets.NODE_HOST}}
            export FIREBASE_PRIVATE_KEY_ID=${{ secrets.FIREBASE_PRIVATE_KEY_ID}}
            export JWT_SECRET=${{ secrets.JWT_SECRET}}
            export RAZORPAY_KEY=${{ secrets.RAZORPAY_KEY}}
            export RAZORPAY_SECRET=${{ secrets.RAZORPAY_SECRET}}
            docker compose  -f docker-compose.prod.yml --profile prod down
            docker compose  -f docker-compose.prod.yml --profile prod pull
            docker compose  -f docker-compose.prod.yml --profile prod up -d

      - name: Run db migrations
        run: npm run db:push

      - name: Run db seed
        run: npm run db:seed
